#!/bin/bash
# helm.sh - Docker Compose to Helm Chart conversion
# Part of docker-to-podman migration tool

# Guard against multiple loading
[[ -n "${_HELM_LOADED:-}" ]] && return 0
_HELM_LOADED=1

_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -z "${_UTILS_LOADED:-}" ]] && source "$_LIB_DIR/utils.sh"
[[ -z "${_PARSER_LOADED:-}" ]] && source "$_LIB_DIR/parser.sh"
[[ -z "${_KUBERNETES_LOADED:-}" ]] && source "$_LIB_DIR/kubernetes.sh"

# Helm Chart output directory
HELM_OUTPUT_DIR="${HELM_OUTPUT_DIR:-./charts}"

# Generate Chart.yaml
generate_chart_yaml() {
    local project_name="$1"
    local output_dir="$2"

    local output_file="${output_dir}/Chart.yaml"

    cat > "$output_file" << EOF
# Helm Chart for ${project_name}
# Generated by docker-to-podman migration tool
apiVersion: v2
name: ${project_name}
description: A Helm chart for ${project_name} (migrated from docker-compose)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - docker-compose
  - migration
  - podman
maintainers:
  - name: docker-to-podman
    url: https://github.com/containers/podman
EOF

    log_success "Generated: $output_file"
}

# Generate values.yaml
generate_values_yaml() {
    local file="$1"
    local project_name="$2"
    local output_dir="$3"

    local output_file="${output_dir}/values.yaml"

    cat > "$output_file" << EOF
# Default values for ${project_name}
# Generated by docker-to-podman migration tool
# This is a YAML-formatted file.

# Global settings
global:
  namespace: default

# Service-specific configurations
EOF

    local services
    services=$(get_services "$file")

    while IFS= read -r service; do
        [[ -z "$service" ]] && continue

        local image ports memory cpus
        image=$(get_service_image "$file" "$service")
        ports=$(get_service_ports "$file" "$service")
        memory=$(get_service_resource "$file" "$service" "memory")
        cpus=$(get_service_resource "$file" "$service" "cpus")

        # Parse image into repository and tag
        local repo tag
        if [[ "$image" == *":"* ]]; then
            repo="${image%:*}"
            tag="${image##*:}"
        else
            repo="$image"
            tag="latest"
        fi

        cat >> "$output_file" << EOF

${service}:
  enabled: true
  replicaCount: 1

  image:
    repository: ${repo}
    tag: "${tag}"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
EOF

        # Add ports
        if [[ -n "$ports" ]]; then
            echo "    ports:" >> "$output_file"
            while IFS= read -r port; do
                [[ -z "$port" ]] && continue
                local parsed_port
                parsed_port=$(parse_port "$port")
                local host_port="${parsed_port%%:*}"
                local container_port="${parsed_port#*:}"
                container_port="${container_port%/*}"
                echo "      - port: ${host_port}" >> "$output_file"
                echo "        targetPort: ${container_port}" >> "$output_file"
            done <<< "$ports"
        fi

        cat >> "$output_file" << EOF

  resources:
    limits:
      cpu: ${cpus:-"500m"}
      memory: ${memory:-"256Mi"}
    requests:
      cpu: "100m"
      memory: "128Mi"

  nodeSelector: {}
  tolerations: []
  affinity: {}
EOF

        # Add environment variables
        local environment
        environment=$(get_service_environment "$file" "$service")
        if [[ -n "$environment" ]]; then
            echo "" >> "$output_file"
            echo "  env:" >> "$output_file"
            while IFS= read -r env; do
                [[ -z "$env" ]] && continue
                local key="${env%%=*}"
                local value="${env#*=}"
                echo "    ${key}: \"${value}\"" >> "$output_file"
            done <<< "$environment"
        fi

    done <<< "$services"

    log_success "Generated: $output_file"
}

# Generate _helpers.tpl
generate_helpers_tpl() {
    local project_name="$1"
    local output_dir="$2"

    local output_file="${output_dir}/templates/_helpers.tpl"

    cat > "$output_file" << 'EOF'
{{/*
Expand the name of the chart.
*/}}
{{- define "chart.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "chart.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "chart.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "chart.labels" -}}
helm.sh/chart: {{ include "chart.chart" . }}
{{ include "chart.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "chart.selectorLabels" -}}
app.kubernetes.io/name: {{ include "chart.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
EOF

    log_success "Generated: $output_file"
}

# Generate deployment template
generate_deployment_template() {
    local file="$1"
    local service="$2"
    local output_dir="$3"

    local output_file="${output_dir}/templates/${service}-deployment.yaml"

    cat > "$output_file" << EOF
{{- if .Values.${service}.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-${service}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: ${service}
spec:
  replicas: {{ .Values.${service}.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ${service}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ${service}
    spec:
      containers:
        - name: ${service}
          image: "{{ .Values.${service}.image.repository }}:{{ .Values.${service}.image.tag }}"
          imagePullPolicy: {{ .Values.${service}.image.pullPolicy }}
EOF

    # Add ports
    local ports
    ports=$(get_service_ports "$file" "$service")
    if [[ -n "$ports" ]]; then
        echo "          ports:" >> "$output_file"
        while IFS= read -r port; do
            [[ -z "$port" ]] && continue
            local parsed_port
            parsed_port=$(parse_port "$port")
            local container_port="${parsed_port#*:}"
            container_port="${container_port%/*}"
            echo "            - containerPort: ${container_port}" >> "$output_file"
        done <<< "$ports"
    fi

    cat >> "$output_file" << EOF
          {{- if .Values.${service}.env }}
          env:
            {{- range \$key, \$value := .Values.${service}.env }}
            - name: {{ \$key }}
              value: {{ \$value | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.${service}.resources | nindent 12 }}
      {{- with .Values.${service}.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.${service}.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.${service}.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
EOF

    log_success "Generated: $output_file"
}

# Generate service template
generate_service_template() {
    local file="$1"
    local service="$2"
    local output_dir="$3"

    local ports
    ports=$(get_service_ports "$file" "$service")

    if [[ -z "$ports" ]]; then
        return 0
    fi

    local output_file="${output_dir}/templates/${service}-service.yaml"

    cat > "$output_file" << EOF
{{- if .Values.${service}.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-${service}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: ${service}
spec:
  type: {{ .Values.${service}.service.type }}
  ports:
    {{- range .Values.${service}.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: port-{{ .targetPort }}
    {{- end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ${service}
{{- end }}
EOF

    log_success "Generated: $output_file"
}

# Generate NOTES.txt
generate_notes_txt() {
    local project_name="$1"
    local output_dir="$2"

    local output_file="${output_dir}/templates/NOTES.txt"

    cat > "$output_file" << 'EOF'
Thank you for installing {{ .Chart.Name }}.

Your release is named {{ .Release.Name }}.

To learn more about the release, try:

  $ helm status {{ .Release.Name }}
  $ helm get all {{ .Release.Name }}

To access your services:

  $ kubectl get svc -l "app.kubernetes.io/instance={{ .Release.Name }}"

Generated by docker-to-podman migration tool.
EOF

    log_success "Generated: $output_file"
}

# Generate .helmignore
generate_helmignore() {
    local output_dir="$1"

    local output_file="${output_dir}/.helmignore"

    cat > "$output_file" << 'EOF'
# Patterns to ignore when building packages.
.DS_Store
.git/
.gitignore
.bzr/
.bzrignore
.hg/
.hgignore
.svn/
*.swp
*.bak
*.tmp
*.orig
*~
.project
.idea/
*.tmproj
.vscode/
EOF

    log_success "Generated: $output_file"
}

# Generate complete Helm chart
generate_helm_chart() {
    local file="$1"
    local project_name="$2"
    local output_dir="${3:-$HELM_OUTPUT_DIR}/${project_name}"

    log_info "Generating Helm chart for project: $project_name"
    log_info "Output directory: $output_dir"

    # Create chart structure
    mkdir -p "$output_dir/templates"

    # Generate chart files
    generate_chart_yaml "$project_name" "$output_dir"
    generate_values_yaml "$file" "$project_name" "$output_dir"
    generate_helpers_tpl "$project_name" "$output_dir"
    generate_helmignore "$output_dir"
    generate_notes_txt "$project_name" "$output_dir"

    # Generate templates for each service
    local services
    services=$(get_services "$file")
    while IFS= read -r service; do
        [[ -z "$service" ]] && continue
        generate_deployment_template "$file" "$service" "$output_dir"
        generate_service_template "$file" "$service" "$output_dir"
    done <<< "$services"

    echo ""
    log_success "=== Helm Chart Generated ==="
    echo ""
    log_info "Chart location: $output_dir"
    echo ""
    log_info "To install the chart:"
    echo ""
    echo "  # Install with default values"
    echo "  helm install ${project_name} $output_dir"
    echo ""
    echo "  # Install with custom values"
    echo "  helm install ${project_name} $output_dir -f custom-values.yaml"
    echo ""
    echo "  # Dry run to see what would be deployed"
    echo "  helm install ${project_name} $output_dir --dry-run --debug"
    echo ""
    log_info "To validate the chart:"
    echo "  helm lint $output_dir"
}

# Check Helm requirements
check_helm_requirements() {
    log_info "Checking Helm requirements..."

    if command -v helm &>/dev/null; then
        local helm_version
        helm_version=$(helm version --short 2>/dev/null)
        log_success "helm: $helm_version"
        return 0
    else
        log_warning "helm: not found"
        log_info "Install helm from: https://helm.sh/docs/intro/install/"
        return 1
    fi
}
