#!/bin/bash
# quadlet.sh - Quadlet file generation for Podman 4.4+

# Guard against multiple loading
[[ -n "${_QUADLET_LOADED:-}" ]] && return 0
_QUADLET_LOADED=1

_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -z "${_UTILS_LOADED:-}" ]] && source "$_LIB_DIR/utils.sh"
[[ -z "${_PARSER_LOADED:-}" ]] && source "$_LIB_DIR/parser.sh"
[[ -z "${_SELINUX_LOADED:-}" ]] && source "$_LIB_DIR/selinux.sh"
[[ -z "${_CONVERTER_LOADED:-}" ]] && source "$_LIB_DIR/converter.sh"

# Generate .container file for a service
generate_container_file() {
    local file="$1"
    local service="$2"
    local project_name="$3"
    local output_dir="$4"

    local container_name="${project_name}-${service}"
    local output_file="${output_dir}/${container_name}.container"

    # Get service properties using getter functions
    local image
    image=$(get_service_image "$file" "$service")
    if [[ -z "$image" ]]; then
        log_error "Service '$service' has no image defined"
        return 1
    fi
    image=$(normalize_image "$image")

    local ports volumes environment depends_on networks
    local command entrypoint restart memory cpus
    local env_file labels user working_dir
    local security_opt cap_add cap_drop privileged
    local network_mode ipc_mode pid_mode userns_mode
    local tmpfs_mounts devices read_only

    ports=$(get_service_ports "$file" "$service")
    volumes=$(get_service_volumes "$file" "$service")
    environment=$(get_service_environment "$file" "$service")
    depends_on=$(get_service_depends_on "$file" "$service")
    networks=$(get_service_networks "$file" "$service")
    command=$(get_service_command "$file" "$service")
    entrypoint=$(get_service_entrypoint "$file" "$service")
    restart=$(get_service_restart "$file" "$service")
    memory=$(get_service_resource "$file" "$service" "memory")
    cpus=$(get_service_resource "$file" "$service" "cpus")
    env_file=$(get_service_env_file "$file" "$service")
    labels=$(get_service_labels "$file" "$service")
    user=$(get_service_user "$file" "$service")
    working_dir=$(get_service_working_dir "$file" "$service")
    security_opt=$(get_service_security_opt "$file" "$service")
    cap_add=$(get_service_cap_add "$file" "$service")
    cap_drop=$(get_service_cap_drop "$file" "$service")
    privileged=$(get_service_privileged "$file" "$service")
    network_mode=$(get_service_network_mode "$file" "$service")
    ipc_mode=$(get_service_ipc "$file" "$service")
    pid_mode=$(get_service_pid "$file" "$service")
    userns_mode=$(get_service_userns_mode "$file" "$service")
    tmpfs_mounts=$(get_service_tmpfs "$file" "$service")
    devices=$(get_service_devices "$file" "$service")
    read_only=$(get_service_read_only "$file" "$service")

    cat > "$output_file" << EOF
# Quadlet container file for $service
# Generated by docker-to-podman migration tool
# Documentation: https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html

[Unit]
Description=$service container (migrated from docker-compose)
EOF

    # Add dependencies
    if [[ -n "$depends_on" ]]; then
        while IFS= read -r dep; do
            [[ -z "$dep" ]] && continue
            echo "After=${project_name}-${dep}.service" >> "$output_file"
            echo "Requires=${project_name}-${dep}.service" >> "$output_file"
        done <<< "$depends_on"
    fi

    # Container section
    cat >> "$output_file" << EOF

[Container]
Image=$image
ContainerName=$container_name
EOF

    # Ports
    while IFS= read -r port; do
        [[ -z "$port" ]] && continue
        local parsed_port
        parsed_port=$(parse_port "$port")
        echo "PublishPort=$parsed_port" >> "$output_file"
    done <<< "$ports"

    # Volumes
    while IFS= read -r vol; do
        [[ -z "$vol" ]] && continue
        local converted_vol
        converted_vol=$(convert_volume_mount "$vol" "$project_name")
        echo "Volume=$converted_vol" >> "$output_file"
    done <<< "$volumes"

    # Environment variables
    while IFS= read -r env; do
        [[ -z "$env" ]] && continue
        echo "Environment=$env" >> "$output_file"
    done <<< "$environment"

    # Networks
    local has_network=false
    while IFS= read -r net; do
        [[ -z "$net" ]] && continue
        has_network=true
        echo "Network=${project_name}-${net}.network" >> "$output_file"
    done <<< "$networks"

    # If no network specified, use default pod network
    if [[ "$has_network" == "false" ]]; then
        echo "Network=${project_name}.network" >> "$output_file"
    fi

    # Resource limits
    [[ -n "$memory" ]] && echo "PodmanArgs=--memory=${memory}" >> "$output_file"
    [[ -n "$cpus" ]] && echo "PodmanArgs=--cpus=${cpus}" >> "$output_file"

    # Security options
    if [[ -n "$security_opt" ]]; then
        while IFS= read -r opt; do
            [[ -z "$opt" ]] && continue
            if [[ "$opt" == label:type:* ]]; then
                echo "SecurityLabelType=${opt#label:type:}" >> "$output_file"
            else
                echo "PodmanArgs=--security-opt=${opt}" >> "$output_file"
            fi
        done <<< "$security_opt"
    fi

    # Capabilities
    while IFS= read -r cap; do
        [[ -z "$cap" ]] && continue
        echo "AddCapability=${cap}" >> "$output_file"
    done <<< "$cap_add"

    while IFS= read -r cap; do
        [[ -z "$cap" ]] && continue
        echo "DropCapability=${cap}" >> "$output_file"
    done <<< "$cap_drop"

    # Privileged mode
    if [[ "$privileged" == "true" ]]; then
        echo "SecurityLabelType=spc_t" >> "$output_file"
        echo "PodmanArgs=--privileged" >> "$output_file"
    fi

    # Namespace modes
    if [[ -n "$network_mode" ]]; then
        case "$network_mode" in
            host) echo "Network=host" >> "$output_file" ;;
            none) echo "Network=none" >> "$output_file" ;;
            service:*) echo "PodmanArgs=--network=container:${network_mode#service:}" >> "$output_file" ;;
            container:*) echo "PodmanArgs=--network=${network_mode}" >> "$output_file" ;;
        esac
    fi

    [[ -n "$ipc_mode" ]] && echo "PodmanArgs=--ipc=${ipc_mode}" >> "$output_file"
    [[ -n "$pid_mode" ]] && echo "PodmanArgs=--pid=${pid_mode}" >> "$output_file"
    [[ -n "$userns_mode" ]] && echo "PodmanArgs=--userns=${userns_mode}" >> "$output_file"

    # Tmpfs mounts
    while IFS= read -r tmpfs; do
        [[ -z "$tmpfs" ]] && continue
        echo "Tmpfs=${tmpfs}" >> "$output_file"
    done <<< "$tmpfs_mounts"

    # Devices
    while IFS= read -r device; do
        [[ -z "$device" ]] && continue
        echo "AddDevice=${device}" >> "$output_file"
    done <<< "$devices"

    # Read-only root filesystem
    [[ "$read_only" == "true" ]] && echo "ReadOnly=true" >> "$output_file"

    # User
    [[ -n "$user" ]] && echo "User=${user}" >> "$output_file"

    # Working directory
    [[ -n "$working_dir" ]] && echo "WorkingDir=${working_dir}" >> "$output_file"

    # Labels
    while IFS= read -r label; do
        [[ -z "$label" ]] && continue
        echo "Label=$label" >> "$output_file"
    done <<< "$labels"

    # Environment files
    while IFS= read -r ef; do
        [[ -z "$ef" ]] && continue
        # Convert relative paths to absolute
        if [[ "$ef" == ./* ]] || [[ "$ef" == ../* ]]; then
            local compose_dir
            compose_dir=$(dirname "$file")
            ef="$compose_dir/$ef"
        fi
        echo "EnvironmentFile=$ef" >> "$output_file"
    done <<< "$env_file"

    # Entrypoint
    [[ -n "$entrypoint" ]] && echo "Entrypoint=${entrypoint}" >> "$output_file"

    # Command
    [[ -n "$command" ]] && echo "Exec=${command}" >> "$output_file"

    # Health check
    local healthcheck_test
    healthcheck_test=$(get_service_healthcheck "$file" "$service" "test")
    if [[ -n "$healthcheck_test" ]]; then
        healthcheck_test=$(echo "$healthcheck_test" | sed 's/^\[//' | sed 's/\]$//' | sed 's/"//g' | sed 's/,/ /g')
        healthcheck_test=$(echo "$healthcheck_test" | sed 's/^CMD-SHELL //' | sed 's/^CMD //')
        echo "HealthCmd=$healthcheck_test" >> "$output_file"

        local interval timeout retries
        interval=$(get_service_healthcheck "$file" "$service" "interval")
        timeout=$(get_service_healthcheck "$file" "$service" "timeout")
        retries=$(get_service_healthcheck "$file" "$service" "retries")

        [[ -n "$interval" ]] && echo "HealthInterval=$interval" >> "$output_file"
        [[ -n "$timeout" ]] && echo "HealthTimeout=$timeout" >> "$output_file"
        [[ -n "$retries" ]] && echo "HealthRetries=$retries" >> "$output_file"
    fi

    # Performance optimizations
    echo "" >> "$output_file"
    echo "# Performance optimizations" >> "$output_file"
    echo "AutoUpdate=registry" >> "$output_file"

    # Service section
    cat >> "$output_file" << EOF

[Service]
Restart=$(convert_restart_policy "$restart")
TimeoutStartSec=300

[Install]
WantedBy=default.target
EOF

    log_success "Generated: $output_file"
}

# Generate .network file
generate_network_file() {
    local file="$1"
    local network="$2"
    local project_name="$3"
    local output_dir="$4"

    local network_name="${project_name}-${network}"
    local output_file="${output_dir}/${network_name}.network"
    local driver
    driver=$(get_network_driver "$file" "$network")

    cat > "$output_file" << EOF
# Quadlet network file for $network
# Generated by docker-to-podman migration tool

[Network]
NetworkName=$network_name
Driver=$driver

# Performance: Use pasta for better performance (Podman 4.4+)
# Uncomment if needed:
# Options=pasta

[Install]
WantedBy=default.target
EOF

    log_success "Generated: $output_file"
}

# Generate default network file
generate_default_network_file() {
    local project_name="$1"
    local output_dir="$2"

    local output_file="${output_dir}/${project_name}.network"

    cat > "$output_file" << EOF
# Default network for $project_name
# Generated by docker-to-podman migration tool

[Network]
NetworkName=$project_name
Driver=bridge

[Install]
WantedBy=default.target
EOF

    log_success "Generated: $output_file"
}

# Generate .volume file
generate_volume_file() {
    local file="$1"
    local volume="$2"
    local project_name="$3"
    local output_dir="$4"

    local volume_name="${project_name}_${volume}"
    local output_file="${output_dir}/${volume_name}.volume"

    cat > "$output_file" << EOF
# Quadlet volume file for $volume
# Generated by docker-to-podman migration tool

[Volume]
VolumeName=$volume_name

[Install]
WantedBy=default.target
EOF

    log_success "Generated: $output_file"
}

# Generate all Quadlet files for a docker-compose project
generate_quadlet_files() {
    local file="$1"
    local project_name="$2"
    local output_dir="$3"
    local install="${4:-false}"

    log_info "Generating Quadlet files for project: $project_name"

    # Create output directory
    mkdir -p "$output_dir"

    # Generate default network
    generate_default_network_file "$project_name" "$output_dir"

    # Generate network files
    local networks
    networks=$(get_networks "$file")
    while IFS= read -r network; do
        [[ -z "$network" ]] && continue
        generate_network_file "$file" "$network" "$project_name" "$output_dir"
    done <<< "$networks"

    # Generate volume files
    local volumes
    volumes=$(get_volumes "$file")
    while IFS= read -r volume; do
        [[ -z "$volume" ]] && continue
        generate_volume_file "$file" "$volume" "$project_name" "$output_dir"
    done <<< "$volumes"

    # Generate container files
    local services
    services=$(get_services "$file")
    while IFS= read -r service; do
        [[ -z "$service" ]] && continue
        generate_container_file "$file" "$service" "$project_name" "$output_dir"
    done <<< "$services"

    log_success "All Quadlet files generated in: $output_dir"

    # Install if requested
    if [[ "$install" == "true" ]]; then
        install_quadlet_files "$output_dir"
    fi
}

# Install Quadlet files to systemd directory
install_quadlet_files() {
    local source_dir="$1"
    local mode="${2:-user}"

    local quadlet_dir
    quadlet_dir=$(ensure_quadlet_dir "$mode")

    log_info "Installing Quadlet files to: $quadlet_dir"

    # Copy all Quadlet files
    cp "$source_dir"/*.container "$quadlet_dir/" 2>/dev/null || true
    cp "$source_dir"/*.network "$quadlet_dir/" 2>/dev/null || true
    cp "$source_dir"/*.volume "$quadlet_dir/" 2>/dev/null || true

    # Reload systemd
    if [[ "$mode" == "user" ]]; then
        systemctl --user daemon-reload
        log_info "Reloaded user systemd daemon"
    else
        systemctl daemon-reload
        log_info "Reloaded system systemd daemon"
    fi

    log_success "Quadlet files installed successfully!"
    log_info "To start services, use: systemctl --user start <service-name>"
}

# List generated services
list_quadlet_services() {
    local project_name="$1"
    local mode="${2:-user}"

    log_info "Services for project '$project_name':"

    if [[ "$mode" == "user" ]]; then
        systemctl --user list-units --type=service "${project_name}-*" 2>/dev/null || true
    else
        systemctl list-units --type=service "${project_name}-*" 2>/dev/null || true
    fi
}

# Start all services for a project
start_quadlet_services() {
    local project_name="$1"
    local mode="${2:-user}"

    log_info "Starting all services for project: $project_name"

    local quadlet_dir
    quadlet_dir=$(get_quadlet_dir "$mode")

    # Start networks first
    for f in "${quadlet_dir}/${project_name}"*.network; do
        [[ -f "$f" ]] || continue
        local service_name
        service_name=$(basename "$f" .network)
        if [[ "$mode" == "user" ]]; then
            systemctl --user start "${service_name}-network.service" 2>/dev/null || true
        else
            systemctl start "${service_name}-network.service" 2>/dev/null || true
        fi
    done

    # Then start containers
    for f in "${quadlet_dir}/${project_name}"*.container; do
        [[ -f "$f" ]] || continue
        local service_name
        service_name=$(basename "$f" .container)
        log_info "Starting: $service_name"
        if [[ "$mode" == "user" ]]; then
            systemctl --user start "${service_name}.service"
        else
            systemctl start "${service_name}.service"
        fi
    done

    log_success "All services started!"
}

# Stop all services for a project
stop_quadlet_services() {
    local project_name="$1"
    local mode="${2:-user}"

    log_info "Stopping all services for project: $project_name"

    local quadlet_dir
    quadlet_dir=$(get_quadlet_dir "$mode")

    for f in "${quadlet_dir}/${project_name}"*.container; do
        [[ -f "$f" ]] || continue
        local service_name
        service_name=$(basename "$f" .container)
        log_info "Stopping: $service_name"
        if [[ "$mode" == "user" ]]; then
            systemctl --user stop "${service_name}.service" 2>/dev/null || true
        else
            systemctl stop "${service_name}.service" 2>/dev/null || true
        fi
    done

    log_success "All services stopped!"
}

# Enable all services for a project (auto-start on boot)
enable_quadlet_services() {
    local project_name="$1"
    local mode="${2:-user}"

    log_info "Enabling auto-start for project: $project_name"

    local quadlet_dir
    quadlet_dir=$(get_quadlet_dir "$mode")

    for f in "${quadlet_dir}/${project_name}"*.container; do
        [[ -f "$f" ]] || continue
        local service_name
        service_name=$(basename "$f" .container)
        if [[ "$mode" == "user" ]]; then
            systemctl --user enable "${service_name}.service"
        else
            systemctl enable "${service_name}.service"
        fi
    done

    log_success "Auto-start enabled for all services!"
}

# Disable all services for a project (disable auto-start on boot)
disable_quadlet_services() {
    local project_name="$1"
    local mode="${2:-user}"

    log_info "Disabling auto-start for project: $project_name"

    local quadlet_dir
    quadlet_dir=$(get_quadlet_dir "$mode")

    for f in "${quadlet_dir}/${project_name}"*.container; do
        [[ -f "$f" ]] || continue
        local service_name
        service_name=$(basename "$f" .container)
        if [[ "$mode" == "user" ]]; then
            systemctl --user disable "${service_name}.service" 2>/dev/null || true
        else
            systemctl disable "${service_name}.service" 2>/dev/null || true
        fi
    done

    log_success "Auto-start disabled for all services!"
}

# Export running containers as docker-compose.yml
export_to_compose() {
    local project_name="$1"
    local output_file="${2:-docker-compose.exported.yml}"

    log_info "Exporting containers for project: $project_name"

    # Get all containers for the project
    local containers
    containers=$(podman ps -a --filter "name=${project_name}" --format "{{.Names}}" 2>/dev/null)

    if [[ -z "$containers" ]]; then
        log_error "No containers found for project: $project_name"
        return 1
    fi

    cat > "$output_file" << 'EOF'
# Docker Compose file exported from Podman
# Generated by docker-to-podman migration tool
version: '3.8'

services:
EOF

    while IFS= read -r container; do
        [[ -z "$container" ]] && continue

        # Get container details using podman inspect
        local image
        image=$(podman inspect "$container" --format '{{.Config.Image}}' 2>/dev/null)

        # Service name (remove project prefix)
        local service_name="${container#"${project_name}"-}"
        service_name="${service_name#"${project_name}"_}"

        cat >> "$output_file" << EOF
  ${service_name}:
    image: ${image}
    container_name: ${container}
EOF

        # Add ports
        local port_bindings
        port_bindings=$(podman inspect "$container" --format '{{range $p, $conf := .NetworkSettings.Ports}}{{if $conf}}{{(index $conf 0).HostPort}}:{{$p}}{{"\n"}}{{end}}{{end}}' 2>/dev/null)
        if [[ -n "$port_bindings" ]]; then
            echo "    ports:" >> "$output_file"
            while IFS= read -r port; do
                [[ -z "$port" ]] && continue
                echo "      - \"${port}\"" >> "$output_file"
            done <<< "$port_bindings"
        fi

        # Add environment variables
        local env_list
        env_list=$(podman inspect "$container" --format '{{range .Config.Env}}{{.}}{{"\n"}}{{end}}' 2>/dev/null | grep -v '^PATH=' | grep -v '^HOME=' | grep -v '^HOSTNAME=' | head -20)
        if [[ -n "$env_list" ]]; then
            echo "    environment:" >> "$output_file"
            while IFS= read -r env; do
                [[ -z "$env" ]] && continue
                local key="${env%%=*}"
                local value="${env#*=}"
                value="${value//\\/\\\\}"
                value="${value//\"/\\\"}"
                echo "      ${key}: \"${value}\"" >> "$output_file"
            done <<< "$env_list"
        fi

        # Add volumes
        local mounts
        mounts=$(podman inspect "$container" --format '{{range .Mounts}}{{.Source}}:{{.Destination}}{{"\n"}}{{end}}' 2>/dev/null)
        if [[ -n "$mounts" ]]; then
            echo "    volumes:" >> "$output_file"
            while IFS= read -r mount; do
                [[ -z "$mount" ]] && continue
                echo "      - ${mount}" >> "$output_file"
            done <<< "$mounts"
        fi

        echo "" >> "$output_file"

    done <<< "$containers"

    log_success "Exported to: $output_file"
}
